---
- name: Clone git
  hosts: localhost
  any_errors_fatal: true
  gather_facts: no
  vars_prompt:

    - name: git_username
      prompt: Username for Git
      private: no

    - name: git_email
      prompt: Email for Git
      private: no
      
  vars_files:
    - /home/ansible/build/vars/test_vars.yml

  tasks:

  - name: Configuring git
    command: "{{ item }} "
    loop:
      - git config --global user.email "{{ git_email }}"
      - git config --global user.name "{{ git_username }}"

  - name: Cloning a github repository
    git:
      repo: https://github.com/e-veal/splunk-practice-lab
      dest: /home/ansible/build
      clone: yes
      update: yes

  - name: Deleting test folder
    file:
      path: /home/ansible/build/tests
      state: absent
      
  - name: Disconnecting git
    command: "{{ item }}"
    loop:
      - git remote rm main
      - rm -rf .git