---
- name: Build Splunk Forwarder
  hosts: forwarders
  any_errors_fatal: true
  gather_facts: no
  vars_files:
    - ~/build/vars/main_vars.yml

  tasks:

  - name: Checking if wget package is installed
    package_facts:
      manager: "auto"

  - name: Install wget
    yum:
      name: wget
      state: latest
    when: "'wget' not in ansible_facts.packages"

  - name: Checking if Splunk Forwarder is installed
    stat:
      path: /opt/splunkforwarder
    register: stat_result

  - name: Installing Splunk, if not already installed
    become: yes
    become_user: root
    unarchive:
      src: "{{ splunkfwdr_pkg }}"
      dest: /opt
      owner: splunk
      remote_src: yes
    when: not stat_result.stat.exists
  
  - name: Setting environment variables
    lineinfile:
      path: ~/.bashrc
      insertafter: EOF
      line: export SPLUNK_HOME=/opt/splunk/
      create: yes
    become: yes
    become_user: splunk
  
  - name: Updating shell
    shell: source ~/.bashrc
    become: yes
    become_user: splunk

  - name: Starting Splunk Forwarder
    command: '/opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --auto-ports --no-prompt --seed-passwd {{adminPwd}}'
    become: yes
    become_user: splunk