---
- name: Add search peers
  hosts: all
  any_errors_fatal: true
  become: yes
  become_user: splunk
  vars_files:
    - ~/build/vars/test_vars.yml

  tasks:

  - name: Set variables
    set_fact: 
      varCMgr: "{{ hostvars['cm']['ansible_default_ipv4']['address'] }}"
      varSH: "{{ hostvars['sh']['ansible_default_ipv4']['address'] }}"

  - name: Adding search peers
    command: "{{ item }}"
    loop:
      - "/opt/splunk/bin/splunk add search-server https://{{ varSH }}:8089 -auth admin:splunk3du -remoteUsername admin -remotePassword splunk3du"
      - "/opt/splunk/bin/splunk add search-server https://{{ varCMgr }}:8089 -auth admin:splunk3du -remoteUsername admin -remotePassword splunk3du"
    when: inventory_hostname == 'mc'