---
- name: Add search peers
  hosts: "{{active_servers}}"
  any_errors_fatal: true
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:

  - name: Setting variables
    set_fact: 
      varCMgr: "{{ hostvars['CM']['ansible_default_ipv4']['address'] }}"
      varSH: "{{ hostvars['SH']['ansible_default_ipv4']['address'] }}"

  - name: Adding search peers
    command: "{{ item }}"
    loop:
      - "/opt/splunk/bin/splunk add search-server https://{{ varSH }}:8089 -auth admin:{{adminPwd}} -remoteUsername admin -remotePassword {{adminPwd}}"
      - "/opt/splunk/bin/splunk add search-server https://{{ varCMgr }}:8089 -auth admin:{{adminPwd}} -remoteUsername admin -remotePassword {{adminPwd}}"
    when: inventory_hostname == 'MC'