---
# ansible-playbook ~/build/tasks/configure_hf.yml -i inventory -K --check

- name: Forwarders
  hosts: heavy_forwarder
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:
  
  - name: Uploading folders to apps
    copy:
      src: "{{ item }}"
      dest: /opt/splunk/etc/apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_all_deploymentclient
      - /home/ansible/build/files/spe_cluster_forwarder_outputs
      - /home/ansible/build/files/spe_heavy_forwarder_inputs

  - name: Enabling heavy forwarding
    command: /opt/splunk/bin/splunk enable app SplunkForwarder -auth admin:{{adminPwd}}