---
- name: Universal Forwarders
  hosts: forwarders
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:
  
  - name: Uploading folders to apps
    copy:
      src: "{{ item }}"
      dest: /opt/splunkforwarder/etc/apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_universal_forwarder_outputs
      - /home/ansible/build/files/spe_all_deploymentclient
      - /home/ansible/build/files/spe_mail_inputs
      - /home/ansible/build/files/spe_network_inputs
      - /home/ansible/build/files/spe_os_inputs
      - /home/ansible/build/files/Splunk_TA_nix  

  - name: Ensuring receiver is listening
    command: /opt/splunkforwarder/bin/splunk enable listen 9997 -auth admin:{{adminPwd}}