---
- name: Forwarders
  hosts: heavy_forwarder
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:
  
  - name: Uploading folders to apps
    copy:
      src: "{{ item }}"
      dest: /opt/splunkforwarder/etc/apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_cluster_forwarder_outputs
      - /home/ansible/build/files/spe_master_deploymentclient
      - /home/ansible/build/files/spe_uf_inputs

  - name: Ensuring receiver is listening
    command: "{{ item }}"
    loop:
    - /opt/splunkforwarder/bin/splunk enable listen 9997 -auth admin:{{adminPwd}}
    - /opt/splunkforwarder/bin/splunk enable listen 9998 -auth admin:{{adminPwd}}

  - name: Enabling heavy forwarding
    command: "{{ item }}"
    loop:
      - /opt/splunk/bin/splunk enable app SplunkForwarder -auth admin:{{adminPwd}}