---
- name: Cluster Manager
  hosts: cm
  any_errors_fatal: true
  become: yes
  become_user: splunk
  vars_files:
    - ~/build/vars/test_vars.yml

  tasks: 

  - name: Enabling CM server banner
    copy:
      src: ~/build/files/spe_banners/cm-global-banner.conf
      dest: /opt/splunk/etc/system/local/global-banner.conf 

  - name: Uploading folders to apps on cluster manager
    copy:
      src: "{{ item }}"
      dest: /opt/splunk/etc/apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_cluster_master_base
      - /home/ansible/build/files/spe_cluster_forwarder_outputs
      - /home/ansible/build/files/spe_master_deploymentclient
