---
- name: Universal Forwarders
  hosts: forwarders
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:

  - name: Setting default host name
    copy:
      src: /home/ansible/build/files/spe_servernames/uf-inputs.conf
      dest: /opt/splunkforwarder/etc/system/local/inputs.conf 
  
  - name: Uploading folders to apps
    copy:
      src: "{{ item }}"
      dest: /opt/splunkforwarder/etc/apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_cluster_forwarder_outputs
      - /home/ansible/build/files/spe_all_deploymentclient

  - name: Ensuring receiver is listening
    command: /opt/splunkforwarder/bin/splunk enable listen 9997 -auth admin:{{adminPwd}}