---
- name: Forwarders
  hosts: heavy_forwarder
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:
  
  - name: Uploading folders to apps
    copy:
      src: "{{ item }}"
      dest: /opt/splunkforwarder/etc/apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_master_deploymentclient
      - /home/ansible/build/files/spe_heavy_forwarder_outputs

  - name: Enabling heavy forwarding
    command: /opt/splunk/bin/splunk enable app SplunkForwarder -auth admin:{{adminPwd}}