# ansible-playbook ~/build/tasks/configure_sh.yml -i inventory -K
---
- name: Search Head
  hosts: SH
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:

  - name: Enabling SH server banner
    copy:
      src: /home/ansible/build/files/spe_banners/sh-global-banner.conf
      dest: /opt/splunk/etc/system/local/global-banner.conf
      
  - name: Uploading folders to apps
    copy:
      src: "{{ item }}"
      dest: /opt/splunk/etc/apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_cluster_search_base
      - /home/ansible/build/files/spe_cluster_forwarder_outputs
      - /home/ansible/build/files/spe_all_deploymentclient
      - /home/ansible/build/files/spe_all_indexes
      - /home/ansible/build/files/spe_search_volume_indexes