---
- name: Indexers
  hosts: indexers
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:

  - name: Uploading folders to apps on indexers
    copy:
      src: "{{ item }}"
      dest: /opt/splunk/etc/apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_cluster_indexer_base

  - name: Setting default host name
    copy:
      src: /home/ansible/build/files/spe_servernames/idx1-inputs.conf
      dest: /opt/splunk/etc/system/local/inputs.conf 
    when: inventory_hostname == 'IDX1'

  - name: Setting default host name
    copy:
      src: /home/ansible/build/files/spe_servernames/idx2-inputs.conf
      dest: /opt/splunk/etc/system/local/inputs.conf 
    when: inventory_hostname == 'IDX2'