---
# ansible-playbook ~/build/tasks/configure_mc.yml -i inventory -K --check

- name: Monitoring Console
  hosts: MC
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:

  - name: Uploading folders to deployment-apps on monitoring console
    copy:
      src: "{{ item }}"
      dest: /opt/splunk/etc/deployment-apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_inputs_mail
      - /home/ansible/build/files/spe_inputs_network
      - /home/ansible/build/files/spe_inputs_os
      - /home/ansible/build/files/spe_inputs_error
      - /home/ansible/build/files/spe_inputs_Splunk_TA_nix  