---
# ansible-playbook ~/build/tasks/ingest_data.yml -i inventory -K --check

- name: Add data to ingest
  hosts: forwarders:heavy_forwarder
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: root
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:

  - name: Configuring HF
    block:
      - name: Adding data to HF
        copy: 
          src: /home/ansible/build/files/nakia_logs/hf/
          dest: /var/log/
          owner: root
          group: root
      - copy: 
          src: "{{ item }}"
          dest: /opt/splunk/etc/apps/
          owner: root
          group: root
        loop: 
          - /home/ansible/build/files/nakia_logs/spe_linux_maillog_props
      - command: /opt/splunk/bin/splunk restart
    when: inventory_hostname == 'HF'
  
  - name: Configuring UF
    block:
      - name: Adding data to UF
        copy: 
          src: /home/ansible/build/files/nakia_logs/uf/var-log/
          dest: /var/log/
          owner: root
          group: root
      - copy: 
          src: /home/ansible/build/files/nakia_logs/uf/var-data/
          dest: /var/data/
          owner: root
          group: root
      - copy: 
          src: "{{ item }}"
          dest: /opt/splunkforwarder/etc/apps/
          owner: root
          group: root
        loop: 
          - /home/ansible/build/files/nakia_logs/spe_linux_maillog_inputs
          - /home/ansible/build/files/nakia_logs/spe_linux_maillog_props
      - command: /opt/splunkforwarder/bin/splunk restart
    when: inventory_hostname == 'UF'