---
# ansible-playbook ~/build/tasks/ingest_data.yml -i inventory -K --check

- name: Add data to ingest
  hosts: all
  any_errors_fatal: true
  gather_facts: no
  become: yes
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:

  - name: Configuring IDX
    block:
      - name: Adding data to IDX
        copy: 
          src: /home/ansible/build/files/okoye_logs/spe_indexer_orig_fwd_props
          dest: /opt/splunk/etc/master-apps/
          owner: splunk
          group: splunk
    become_user: root
    when: inventory_hostname == 'CM'
  
  - name: Pushing packages to indexers
    command: /opt/splunk/bin/splunk apply cluster-bundle --answer-yes -auth admin:{{adminPwd}}
    when: inventory_hostname == 'CM'
  
  - name: Configuring UF
    block:
      - name: Adding data to UF
        copy: 
          src: /home/ansible/build/files/okoye_logs/uf/var-data/
          dest: /var/data/
          owner: root
          group: root
      - copy: 
          src: /home/ansible/build/files/okoye_logs/spe_linux_syslog_inputs
          dest: /opt/splunkforwarder/etc/apps/
          owner: splunk
          group: splunk
    become_user: splunk
    when: inventory_hostname == 'UF'

  - command: /opt/splunkforwarder/bin/splunk restart
    become_user: splunk
    when: inventory_hostname == 'UF'