---
- name: Installs Splunk
  hosts: "{{active_servers}}"
  gather_facts: no
  any_errors_fatal: true
  vars_files:
    - ~/build/vars/main_vars.yml

  tasks:
  - name: Checking if wget package is installed
    package_facts:
      manager: "auto"

  - name: Install wget
    yum:
      name: wget
      state: latest
    when: "'wget' not in ansible_facts.packages"

  - name: Creating splunk user
    user:
      name: splunk
      groups: 
      - splunk
      update_password: always
      password: "{{ splunk3du|password_hash('sha512') }}"
      state: present
    become: yes
    become_user: root

  - name: Checking if Splunk is installed
    stat:
      path: /opt/splunk
    register: stat_result

  - name: Installing Splunk, if not already installed
    become: yes
    become_user: root
    unarchive:
      src: ~/build/files/{{ splunk_pkg }}
      dest: /opt
      owner: splunk
    when: not stat_result.stat.exists
  
  - name: Setting environment variables
    lineinfile:
      path: ~/.bashrc
      insertafter: EOF
      line: export SPLUNK_HOME=/opt/splunk/
      create: yes
    become: yes
    become_user: splunk

  - name: Deleting installation file
    file:
      path: /home/ansible/{{ splunk_pkg }}
      state: absent
  
  - name: Updating shell
    shell: source ~/.bashrc
    become: yes
    become_user: splunk

  - name: Starting Splunk
    shell: /opt/splunk/bin/splunk start --accept-license --answer-yes --auto-ports --no-prompt --seed-passwd splunk3du
    become: yes
    become_user: splunk