# ansible-playbook ~/build/tasks/install_license.yml -i inventory -K --check
---
- name: Installs License
  hosts: MC
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:

  # - name: Download license
  # - command: "{{ item }}"
  #   loop:
  #     - curl -H 'Authorization: token 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' -H 'Accept: application/vnd.github.v3.raw' -O -L https://api.github.com/e-veal/Splunk/blob/620b01e76fb4d9979d10396cfa66d02dedcaac62/Practice%20Ansible%20Environment/Splunk_Enterprise_NFR_FY23.lic
  #     - mv ~/Splunk_Enterprise_NFR_FY23.lic ~/files/
  
  - name: Uploading license
    copy:
      src: /home/ansible/build/files/Splunk_Enterprise_NFR_FY23.lic
      dest: /opt/splunk/etc/licenses/Splunk_Enterprise_NFR_FY23.lic
    
  - name: Installing license
    command: /opt/splunk/bin/splunk add licenses /opt/splunk/etc/licenses/Splunk_Enterprise_NFR_FY23.lic -auth admin:{{adminPwd}}

  - name: Restarting license server
    command: /opt/splunk/bin/splunk restart