---
- name: Installs Splunk
  hosts: "{{active_servers}}"
  gather_facts: no
  strategy: free
  any_errors_fatal: true
  vars_files:
    - ~/build/vars/main_vars.yml

  tasks:
  - name: Installing Splunk
    block:

      - name: Checking if wget package is installed
        package_facts:
          manager: "auto"
        run_once: yes

      - name: Install wget
        yum:
          name: wget
          state: latest
        when: "'wget' not in ansible_facts.packages"

      - name: Checking if Splunk is installed
        stat:
          path: /opt/splunk
        register: stat_result

      - name: Installing Splunk, if not already installed
        unarchive:
          src: "{{ splunk_pkg }}"
          dest: /opt
          owner: splunk
          remote_src: yes
        when: not stat_result.stat.exists
  
  - name: Configuring Splunk
    block:
    - name: Setting environment variables
      lineinfile:
        path: ~/.bashrc
        insertafter: EOF
        line: export SPLUNK_HOME=/opt/splunk/
        create: yes

    - name: Updating shell
      shell: source ~/.bashrc

    - name: Starting Splunk
      command: '/opt/splunk/bin/splunk start --accept-license --answer-yes --auto-ports --no-prompt --seed-passwd {{adminPwd}}'
    become: yes
    become_user: splunk
