# ansible-playbook ~/build/tasks/main.yml -i inventory -K
---
# tasks file for build
- import_playbook: install_splunk.yml
- import_playbook: non_root.yml
- import_playbook: configure_aio.yml
- import_playbook: update_servername.yml
- import_playbook: install_license.yml