# ansible-playbook ~/build/tasks/main.yml -i inventory --ask-vault-pass
---
# tasks file for dek
- import_playbook: configure_creds.yml
- import_playbook: create_key.yml
- import_playbook: build_ec2.yml