# ansible-playbook ~/build/tasks/non-root.yml -i inventory -K --check
---
- name: 'Configure non-root user'
  hosts: all
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: root
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:
      
  - name: For Enterprise
    block:
    - name: Checking if boot-start is already configured
      stat:
        path: /etc/systemd/system/multi-user.target.wants/Splunkd.service
      register: boot_result
    
    - name: Enabling boot-start on enterprise
      shell: /opt/splunk/bin/splunk enable boot-start -user splunk
      become: yes
      become_user: root
      when: not boot_result.stat.exists

    - name: Changing owner to splunk
      file:
        path: /opt/splunk
        state: directory
        recurse: yes
        owner: splunk
        group: splunk
    when: inventory_hostname not in groups['forwarders']

  - name: For Forwarders
    block:
    - name: Checking if boot-start is already configured
      stat:
        path: /etc/systemd/system/multi-user.target.wants/Splunkd.service
      register: boot_result
      
    - name: Enabling boot-start
      shell: /opt/splunkforwarder/bin/splunk enable boot-start -user splunk
      become: yes
      become_user: root
      when: not boot_result.stat.exists 

    - name: Changing owner to splunk
      file:
        path: /opt/splunkforwarder
        state: directory
        recurse: yes
        owner: splunk
        group: splunk
    when: inventory_hostname in groups['forwarders']

  - name: Checking if init files is exists
    stat:
      path: /etc/init.d/splunk
    register: init_file_result

# if file exists delete it
  - name: Delete file
    file:
      path: /etc/init.d/splunk
      state: absent
    when: init_file_result.stat.exists == true

  - name: Copy file over
    copy:
      src: /home/ansible/build/files/init_splunk_copy
      dest: /tmp
    
  - name: Renaming file
    shell: mv /tmp/init_splunk_copy /etc/init.d/splunk