---
- name: 'Configure non-root user'
  hosts: "{{active_servers}}"
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: root
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:
  
  - name: Checking if boot-start is already configured
    stat:
      path: /etc/systemd/system/multi-user.target.wants/Splunkd.service
    register: boot_result
  
  - name: Enabling boot-start
    shell: /opt/splunk/bin/splunk enable boot-start -user splunk
    become: yes
    become_user: root
    when: not boot_result.stat.exists
  
  - name: Changing owner to splunk
    file:
      path: /opt/splunk
      state: directory
      recurse: yes
      owner: splunk
      group: splunk

  - name: Checking if init files is exists
    stat:
      path: /etc/init.d/splunk
    register: init_file_result

# file doesn't exist
  - name: Copy file over
    copy:
      src: /home/ansible/build/files/init_splunk_copy
      dest: /tmp
    
  - name: Renaming file
    shell: mv /tmp/init_splunk_copy /etc/init.d/splunk
    when: init_file_result.stat.exists == false

# files does exist
  - name: Deleting text
    shell: sed -i -n -E '/case/,$ p' /etc/init.d/splunk
    when: init_file_result.stat.exists

  - name: Merging files
    shell: echo /etc/init.d/splunk >> /tmp/init_splunk_copy && rm /etc/init.d/splunk && mv /tmp/init_splunk_copy /etc/init.d/splunk
    when: init_file_result.stat.exists