- name: Restart splunk
  hosts: all
  any_errors_fatal: true
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main_vars.yml

  tasks:

  - name: Restarting splunk
    command: /opt/splunk/bin/splunk restart
    when: inventory_hostname in groups['gamora']

  - name: Restarting splunk
    command: /opt/splunkforwarder/bin/splunk restart
    when: inventory_hostname in groups['forwarders']