- name: Restart splunk
  hosts: all
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:

  - name: Restarting splunk
    command: /opt/splunk/bin/splunk restart
    when: inventory_hostname in groups['wkabi']

  - name: Restarting forwarders
    command: /opt/splunkforwarder/bin/splunk restart
    when: inventory_hostname in groups['forwarders']
  
  - name: Pushing packages to indexers
    command: /opt/splunk/bin/splunk apply cluster-bundle --answer-yes -auth admin:{{adminPwd}}
    when: inventory_hostname == 'CM'