- name: Restart splunk
  hosts: all_servers
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main_vars.yml

  tasks:

  - name: Restarting splunk
    command: /opt/splunk/bin/splunk restart