---
- name: Update server names
  hosts: all
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - ~/build/vars/main_vars.yml

  tasks:  

  - name: Setting server name on all the hosts in the inventory
    command: "{{ item }}"
    loop:
      - /opt/splunk/bin/splunk set servername {{ inventory_hostname }} -auth admin:{{adminPwd}}
      - /opt/splunk/bin/splunk restart
    when: inventory_hostname in groups['main']

  - name: Setting server name on all the hosts in the inventory
    command: "{{ item }}"
    loop:
      - /opt/splunkforwarder/bin/splunk set servername {{ inventory_hostname }} -auth admin:{{adminPwd}}
      - /opt/splunkforwarder/bin/splunk restart
    when: inventory_hostname in groups['forwarders']