---
- name: Update IPs in base configs
  hosts: all
  any_errors_fatal: true
  vars_files:
    - /home/ansible/build/vars/main_vars.yml

  tasks:  

  - name: Setting variables
    set_fact: 
      varIdx1: "{{ hostvars['IDX1']['ansible_default_ipv4']['address'] }}"
      varIdx2: "{{ hostvars['IDX2']['ansible_default_ipv4']['address'] }}"
      varSh: "{{ hostvars['SH']['ansible_default_ipv4']['address'] }}"
      varCMgr: "{{ hostvars['CM']['ansible_default_ipv4']['address'] }}"
      varUf1: "{{ hostvars['UF1']['ansible_default_ipv4']['address'] }}"
      varUf2: "{{ hostvars['UF2']['ansible_default_ipv4']['address'] }}"

  - name: Updating IPs in all files
    lineinfile:
      path:  /home/ansible/build/files/spe_cluster_forwarder_outputs/local/outputs.conf
      regexp: '^server = '
      line: "server = {{ varIdx1 }}:9997, {{ varIdx2 }}:9997"
    delegate_to: localhost

  - lineinfile:
      path:  /home/ansible/build/files/spe_cluster_search_base/local/server.conf
      regexp: '(manager_uri){1}'
      line: "manager_uri = https://{{ varCMgr }}:8089"
    delegate_to: localhost

  - lineinfile:
      path:  /home/ansible/build/files/spe_cluster_indexer_base/local/server.conf
      regexp: '^manager_uri'
      line: "manager_uri = https://{{ varCMgr }}:8089"
    delegate_to: localhost

  - name: Updating serverclass.conf
    lineinfile:
      path:  /home/ansible/build/files/serverclass.conf
      insertafter: ^\[serverClass:all_deploymentclients\]
      line: "{{ item }}"
    loop:
      - "whitelist.2 = {{ varSh }}"
      - "whitelist.1 = {{ varUf2 }}"
      - "whitelist.0 = {{ varUf1 }}"
    delegate_to: localhost

  - lineinfile:
      path:  /home/ansible/build/files/serverclass.conf
      insertafter: ^\[serverClass:cluster_manager\]
      line: "whitelist.0 = {{ varCMgr }}"
    delegate_to: localhost

  - lineinfile:
      path:  /home/ansible/build/files/serverclass.conf
      insertafter: ^\[serverClass:forwarders\]
      line: "{{ item }}"
    loop:
      - "whitelist.1 = {{ varUf1 }}"
      - "whitelist.0 = {{ varUf2 }}"
    delegate_to: localhost

  - lineinfile:
      path:  /home/ansible/build/files/serverclass.conf
      insertafter: ^\[serverClass:search_head\]
      line: "whitelist.0 = {{ varSh }}"
      firstmatch: yes
    delegate_to: localhost