---
- name: Update IPs in base configs
  hosts: all
  any_errors_fatal: true
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:  

  - name: Setting variables
    set_fact: 
      varMC: "{{ hostvars['MC']['ansible_default_ipv4']['address'] }}"
      varSH: "{{ hostvars['SH']['ansible_default_ipv4']['address'] }}"
      varCM: "{{ hostvars['CM']['ansible_default_ipv4']['address'] }}"
      varIDX1: "{{ hostvars['IDX1']['ansible_default_ipv4']['address'] }}"
      varIDX2: "{{ hostvars['IDX2']['ansible_default_ipv4']['address'] }}"
      varUF1: "{{ hostvars['UF1']['ansible_default_ipv4']['address'] }}"
      varHF1: "{{ hostvars['HF1']['ansible_default_ipv4']['address'] }}"

  - name: Updating IPs in all files
    block: 
      - lineinfile:
          path:  /home/ansible/build/files/spe_cluster_forwarder_outputs/local/outputs.conf
          regexp: '^server = '
          line: "server = {{ varIDX1 }}:9997, {{ varIDX2 }}:9997"

      - lineinfile:
          path:  /home/ansible/build/files/spe_universal_forwarder_outputs/local/outputs.conf
          regexp: '^server = '
          line: "server = {{ varHF1 }}:9997"

      - lineinfile:
          path: "{{ item }}"
          regexp: '^targetUri = '
          line: "targetUri = {{ varMC }}:8089"
        loop:
          - /home/ansible/build/files/spe_master_deploymentclient/local/deploymentclient.conf
          - /home/ansible/build/files/spe_all_deploymentclient/local/deploymentclient.conf

      - lineinfile:
          path:  /home/ansible/build/files/spe_cluster_search_base/local/server.conf
          regexp: '(manager_uri){1}'
          line: "manager_uri = https://{{ varCM }}:8089"

      - lineinfile:
          path:  /home/ansible/build/files/spe_cluster_indexer_base/local/server.conf
          regexp: '^manager_uri'
          line: "manager_uri = https://{{ varCM }}:8089"

      - lineinfile:
          path:  /home/ansible/build/files/spe_cluster_indexer_base/local/server.conf
          regexp: '^master_uri'
          line: "master_uri = https://{{ varMC }}:8089"

      - name: Updating serverclass.conf
        lineinfile:
          path:  /home/ansible/build/files/serverclass.conf
          insertafter: ^\[serverClass:all_deploymentclients\]
          line: "{{ item }}"
        loop:
          - "whitelist.2 = {{ varSH }}"
          - "whitelist.0 = {{ varUF1 }}"

      - lineinfile:
          path:  /home/ansible/build/files/serverclass.conf
          insertafter: ^\[serverClass:cluster_manager\]
          line: "whitelist.0 = {{ varCM }}"

      - lineinfile:
          path:  /home/ansible/build/files/serverclass.conf
          insertafter: ^\[serverClass:forwarders\]
          line: "{{ item }}"
        loop:
          - "whitelist.1 = {{ varUF1 }}"

      - lineinfile:
          path:  /home/ansible/build/files/serverclass.conf
          insertafter: ^\[serverClass:search_head\]
          line: "whitelist.0 = {{ varSH }}"
          firstmatch: yes
    delegate_to: localhost