---
- name: Update server names
  hosts: "{{active_servers}}"
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - ~/build/vars/main_vars.yml

  tasks:  

  - name: Setting server name on all the hosts in the inventory
    command: "{{ item }}"
    loop:
      - /opt/splunk/bin/splunk set servername {{ inventory_hostname }} -auth admin:{{adminPwd}}
      - /opt/splunk/bin/splunk restart