# ansible-playbook ~/build/tasks/configure_cmgr.yml -i inventory -K
---
- name: Cluster Manager
  hosts: CM
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks: 
      
  - name: Uploading folders to apps on cluster manager
    copy:
      src: "{{ item }}"
      dest: /opt/splunk/etc/apps
      owner: splunk
    loop:
      - /home/ansible/build/files/tchalla/spe_cluster_master_base
      - /home/ansible/build/files/spe_cluster_forwarder_outputs
      - /home/ansible/build/files/spe_master_deploymentclient

  - name: Uploading folders to master-apps on cluster manager
    copy:
      src: "{{ item }}"
      dest: /opt/splunk/etc/master-apps
      owner: splunk
    loop:
      - /home/ansible/build/files/tchalla/spe_cluster_indexer_base
      - /home/ansible/build/files/spe_all_indexes
      - /home/ansible/build/files/spe_indexer_volume_indexes