# ansible-playbook ~/build/files/shuri/configure_ds1.yml -i inventory -K
---
- name: Deployment Server
  hosts: DS1
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: splunk
  vars_files:
    - /home/ansible/build/vars/main.yml

  tasks:

  - name: Enabling DS server banner
    copy:
      src: /home/ansible/build/files/shuri/ds1-global-banner.conf
      dest: /opt/splunk/etc/system/local/global-banner.conf

  - name: Configuring serverclasses
    copy:
      src: /home/ansible/build/files/serverclass.conf
      dest: /opt/splunk/etc/system/local/serverclass.conf
      
  - name: Uploading folders to apps on deployment server
    copy:
      src: "{{ item }}"
      dest: /opt/splunk/etc/apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_cluster_forwarder_outputs

  - name: Uploading folders to deployment-apps on deployment server
    copy:
      src: "{{ item }}"
      dest: /opt/splunk/etc/deployment-apps
      owner: splunk
    loop:
      - /home/ansible/build/files/spe_all_indexes
      - /home/ansible/build/files/spe_search_volume_indexes
      - /home/ansible/build/files/spe_indexer_volume_indexes
      - /home/ansible/build/files/spe_cluster_indexer_base
      - /home/ansible/build/files/spe_all_deploymentclient
      - /home/ansible/build/files/spe_inputs_mail
      - /home/ansible/build/files/spe_inputs_network
      - /home/ansible/build/files/spe_inputs_os
      - /home/ansible/build/files/spe_inputs_error
      - /home/ansible/build/files/spe_inputs_Splunk_TA_nix  
  